"""
This Python script enables real-time conversation with OpenAI's ChatGPT model through the terminal.
Generated by ChatGPT, this script establishes a session where the user can interactively ask questions
or have a dialogue with the ChatGPT model. The user's input is sent to the ChatGPT API, and the model's
responses are displayed in the terminal, facilitating a conversational interface. Ensure you have the `openai`
Python package installed and an OpenAI API key set before running this script.
"""

from openai import OpenAI

from openai_cli.env import OPENAI_API_KEY
from openai_cli.logger import logger

client = OpenAI(api_key=OPENAI_API_KEY)


def chat_with_openai():

    conversation = []
    logger.info("ChatGPT: Hello! How can I assist you today?")

    while True:
        user_input = input("> ")
        conversation.append(user_input)

        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": user_input}],
            max_tokens=150,
        )

        answer = response.choices[0].message.content.strip()
        logger.info(f"ChatGPT: {answer}")

        conversation.append(answer)


if __name__ == "__main__":
    chat_with_openai()
